version: "3.8"

services:
  blogWeb:
    build: .
    image: guruwang/blog_web
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.blogWeb.middlewares=redirect-to-https"
        - "traefik.http.routers.blogWeb.entrypoints=web"
        - "traefik.http.routers.blogWeb.rule=Host(`test.ohbital.com`)"

        - "traefik.http.routers.blogWebHttps.middlewares=limit"
        - "traefik.http.routers.blogWebHttps.entrypoints=websecure"
        - "traefik.http.routers.blogWebHttps.rule=Host(`test.ohbital.com`)"
        - "traefik.http.routers.blogWebHttps.tls=true"
        - "traefik.http.routers.blogWebHttps.tls.certresolver=zerossl"
        - "traefik.http.services.blogWebHttps.loadbalancer.server.port=3000"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
